server:
  port: 8081
  servlet:
    context-path: /auth
    session:
      timeout: 30m
      
spring:
  datasource:
    driverClassName: org.h2.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 100
      minimum-idle: 0
    initialization-mode: always
    jdbc-url: ${spring.datasource.url}
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
  session:
    store-type: hazelcast
      
keystore:
  alias: jwt
  location: /keystore/jwt.jks
  password: abcd1234